# Building a Java project
language: java

# We can specify a list of JDKs to be used for testing
jdk:
 - openjdk11
 
 deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - .travis.yml
  on:
    tags: true
    branch: tag
    repo: Abyss-of-Dragon/Travis_CI_Tutorial
    
    notifications:
 email:
   - 10195101542@stu.ecnu.edu.cn


after_success:
  - bash <(curl -s https://codecov.io/bash)
